version: "3.9"
services:
    cms:
        container_name: undiscover-cms
        image: undiscover-cms
        build: ./cms
        ports:
            - "1337:1337"
        volumes:
            - ./cms:/src/app

    blog:
        container_name: undiscover-blog
        image: undiscover-blog
        build: ./blog
        ports:
            - "3000:3000"
        volumes:
            - ./blog:/src/app
            # Mount Strapi uploads folder on Next.js public folder
            - ./cms/public/uploads:/src/app/public/uploads
