version: "3.9"
services:

  cms:
    container_name: undiscover-cms
    image: undiscover-cms
    build: ./cms/
    ports:
      - "1337:1337"
    volumes:
      - ./cms:/srv/app

  blog:
    container_name: undiscover-blog
    image: undiscover-blog
    build: ./blog/
    depends_on: 
      - "cms"
    ports:
      - "3000:3000"
    volumes:
      - ./blog:/srv/app
